geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from products.views import IndexView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('baskets/', include('baskets.urls', namespace='baskets')),
    path('admins/', include('admins.urls', namespace='admins')),
    path('', include('social_django.urls', namespace='social')),
    path('orders/', include('orders.urls', namespace='orders')),
]


if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

orders/urls.py
from django.urls import path

from orders.views import OrderList, order_forming_complete, OrderItemsCreate, OrderReadView, OrderUpdateView, \
    OrderDeleteView, get_product_price

app_name = 'orders'

urlpatterns = [
    path('', OrderList.as_view(), name='order'),
    path('forming/complete/<int:pk>/', order_forming_complete, name='order_forming_complete'),
    path('create/', OrderItemsCreate.as_view(), name='order_create'),
    path('read/<int:pk>/', OrderReadView.as_view(), name='order_read'),
    path('update/<int:pk>/', OrderUpdateView.as_view(), name='order_update'),
    path('delete/<int:pk>/', OrderDeleteView.as_view(), name='order_delete'),
    path('product/<int:pk>/price/', get_product_price),

]

users/urls.py
from django.urls import path
from users.views import RegistrationView, LoginUserView, ProfileUserView, UserLogoutView, verify

app_name = 'users'

urlpatterns = [
    path('login/', LoginUserView.as_view(), name='login'),
    path('registration/', RegistrationView.as_view(), name='registration'),
    path('profile/<int:pk>/', ProfileUserView.as_view(), name='profile'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('verify/<str:email>/<str:activation_key>/', verify, name='verify'),
]

orders/models.py
from django.conf import settings
from django.db import models

# Create your models here.
from products.models import Product


class Order(models.Model):
    FORMING = 'FM'
    SENT_TO_PROCEED = 'STP'
    PROCEEDED = 'PRD'
    PAID = 'PD'
    READY = 'RDY'
    CANCEL = 'CNC'

    ORDER_STATUS_CHOICES = (
        (FORMING, 'формируется'),
        (SENT_TO_PROCEED, 'отправлен в обработку'),
        (PAID, 'оплачен'),
        (PROCEEDED, 'обрабатывается'),
        (READY, 'готов к выдаче'),
        (CANCEL, 'отменен'),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created = models.DateTimeField(verbose_name='создан', auto_now_add=True)
    updated = models.DateTimeField(verbose_name='обновлен', auto_now=True)
    status = models.CharField(verbose_name='статус', max_length=3, choices=ORDER_STATUS_CHOICES, default=FORMING)
    is_active = models.BooleanField(verbose_name='активен', default=True, db_index=True)

    class Meta:
        ordering = ('-created',)
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'

    def __str__(self):
        return f'Текущий заказ: {self.pk}'

    def get_total_quantity(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity, items)))

    def get_product_type_quantity(self):
        return len(self.orderitems.select_related())

    def get_total_cost(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity * x.product.price, items)))

    def delete(self):
        for item in self.orderitems.select_related():
            item.product.quantity += item.quantity
            item.product.save()

        self.is_active = False
        self.save()

    def get_summary(self):
        items = self.orderitems.select_related()
        return {
            'total_cost': sum(list(map(lambda x: x.quantity * x.product.price, items))),
            'total_quantity': sum(list(map(lambda x: x.quantity, items)))
        }


# class OrderItemQuerySet(models.QuerySet):
#
#     def delete(self):
#         for obj in self:
#             obj.product.quantity += obj.quantity
#             obj.product.save()
#         super(OrderItemQuerySet, self).delete()


class OrderItem(models.Model):
    # objects = OrderItemQuerySet.as_manager()
    order = models.ForeignKey(Order, related_name="orderitems", on_delete=models.CASCADE)
    product = models.ForeignKey(Product, verbose_name='продукт', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='количество', default=0)

    def get_product_cost(self):
        return self.product.price * self.quantity

    @staticmethod
    def get_item(pk):
        return OrderItem.objects.filter(pk=pk).first()

    # def delete(self):
    #     self.product.quantity += self.quantity
    #     self.product.save()
    #     super(self.__class__, self).delete()

orders/forms.py
from django import forms
from orders.models import Order, OrderItem
from products.models import Product


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class OrderItemsForm(forms.ModelForm):
    price = forms.CharField(label='цена', required=False)

    class Meta:
        model = OrderItem
        exclude = ()

    def __init__(self, *args, **kwargs):
        super(OrderItemsForm, self).__init__(*args, **kwargs)
        self.fields['product'].queryset = Product.get_items().select_related()
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

orders/views.py
from django.db import transaction
from django.db.models.signals import pre_save, pre_delete
from django.dispatch import receiver
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

from baskets.models import Basket
from common.views import ContextMixin
from orders.forms import OrderItemsForm
from orders.models import Order, OrderItem
from products.models import Product


class OrderList(ContextMixin, ListView):
    model = Order
    template_name = 'orders/order.html'
    title = 'GeekShop - Заказы'

    def get_queryset(self):
        orders = Order.objects.filter(user=self.request.user)
        if self.request.user.is_staff:
            orders = Order.objects.all()
        return orders


class OrderItemsCreate(ContextMixin,CreateView):
    model = Order
    fields = []
    success_url = reverse_lazy('orders:order')
    title = 'GeekShop - новый заказ'

    def get_context_data(self, **kwargs):
        context = super(OrderItemsCreate, self).get_context_data(**kwargs)
        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemsForm, extra=1)

        if self.request.POST:
            formset = OrderFormSet(self.request.POST)
        else:
            basket_items = Basket.objects.filter(user=self.request.user)
            if len(basket_items):
                OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemsForm, extra=len(basket_items))
                formset = OrderFormSet()
                for num, form in enumerate(formset.forms):
                    form.initial['product'] = basket_items[num].product
                    form.initial['quantity'] = basket_items[num].quantity
                    form.initial['price'] = basket_items[num].product.price
                basket_items.delete()
            else:
                formset = OrderFormSet()

        context['orderitems'] = formset

        return context

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            form.instance.user = self.request.user
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()

        if self.object.get_total_cost() == 0:
            self.object.delete()

        return super(OrderItemsCreate, self).form_valid(form)


class OrderUpdateView(ContextMixin, UpdateView):
    model = Order
    fields = []
    success_url = reverse_lazy('orders:order')
    title = 'GeekShop - редактирование заказа'

    def get_context_data(self, **kwargs):
        context = super(OrderUpdateView, self).get_context_data(**kwargs)
        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemsForm, extra=1)

        if self.request.POST:
            formset = OrderFormSet(self.request.POST, instance=self.object)
        else:
            queryset = self.object.orderitems.select_related()
            formset = OrderFormSet(instance=self.object, queryset=queryset)
            for form in formset.forms:
                if form.instance.pk:
                    form.initial['price'] = form.instance.product.price

        context['orderitems'] = formset

        return context

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()

        if self.object.get_total_cost() == 0:
            self.object.delete()

        return super(OrderUpdateView, self).form_valid(form)


class OrderDeleteView(DeleteView):
    model = Order
    success_url = reverse_lazy('orders:order')


class OrderReadView(ContextMixin, DetailView):
    model = Order
    template_name = 'orders/order_read.html'
    title = 'GeekShop - заказ'


def order_forming_complete(request, pk):
    order = get_object_or_404(Order, pk=pk)
    order.status = Order.SENT_TO_PROCEED
    order.save()

    return HttpResponseRedirect(reverse('orders:order'))


@receiver(pre_save, sender=OrderItem)
@receiver(pre_save, sender=Basket)
def product_quantity_update_save(sender, update_fields, instance, **kwargs):
    if update_fields == 'quantity' 'product':
        if instance.pk:
            instance.product.quantity -= instance.quantity.sender.get_item(instance.pk).quantity
        else:
            instance.product.quantity -= instance.quantity
        instance.save()


@receiver(pre_delete, sender=OrderItem)
@receiver(pre_delete, sender=Basket)
def product_quantity_update_delete(sender, instance, **kwargs):
    instance.product.quantity += instance.quantity
    instance.product.save()


def get_product_price(request, pk):
    if request.is_ajax():
        product = Product.objects.filter(pk=int(pk)).first()
        if product:
            return JsonResponse({'price': product.price})
        else:
            return JsonResponse({'price': 0})

orders/templates/orders/order.html
{% extends 'products/base.html' %}
{% load static %}

{% block css %}
<link href="{% static 'css/profile.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

<div class="container">
    <div class="h2 text-center head card-footer ">
        Ваши заказы, {{ user.username}}
    </div>
    <table class="table orders_list card-footer">
        <thead>
        <tr>
            <th>ID</th>
            <th>Заказчик</th>
            <th>Создан</th>
            <th>Обновлен</th>
            <th>Статус</th>
        </tr>
        </thead>
        <tbody>
        {% for item in object_list %}
        {% if item.is_active %}
        <tr>
            <td class="card-footer ">{{ item.pk }}</td>
            <td>{{ item.user.last_name }}  {{ item.user.first_name }}</td>
            <td>{{ item.created|date:"Y-m-d H:i:s" }}</td>
            <td>{{ item.updated|date:"Y-m-d H:i:s" }}</td>
            <td>{{ item.get_status_display }}</td>
            <td>
                <a class="btn btn-outline-success" href="{% url 'orders:order_read' item.pk %}">
                    посмотреть
                </a>
            </td>
            <td>
                {% if item.status == 'FM' %}
                <a class="btn btn-outline-success" href="{% url 'orders:order_update' item.pk %}">
                    редактировать
                </a>
                {% endif %}
            </td>
            <td>
                {% if item.status == 'FM' %}
                <a class="btn btn-outline-success" href="{% url 'orders:order_delete' item.pk %}">
                    удалить
                </a>
                {% endif %}
            </td>
        </tr>
        {% endif %}
        {% endfor %}
        </tbody>
    </table>
        <a href="{% url 'orders:order_create' %}" class="btn btn-info btn-block">
            новый
        </a>
</div>
{% endblock %}

orders/templates/orders/order_confirm_delete.html
{% extends 'products/base.html' %}
{% load static %}

{% block css %}
<link href="{% static 'css/profile.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="container">
    <div class="h2 text-center card-footer ">Уверены, что хотите удалить?
        {% include 'orders/includes/inc_order_summary.html' %}
        <form action="{% url 'orders:order_delete' object.pk %}" method="post">
            {% csrf_token %}
            <div class=" text-center">
                <input class="btn btn-danger" type="submit" value="удалить">
                <a class="btn btn-success " href="{% url 'orders:order' %}">отмена</a>
            </div>
        </form>
    </div>
</div>

{% endblock %}

orders/templates/orders/order_form.html
{% extends "products/base.html" %}
{% load static %}
{% load cache %}

{% block css %}
<link href="{% static 'css/profile.css' %}" rel="stylesheet">
{% endblock %}

{% block js %}
<script src="{% static 'js/orders_scripts.js' %}"></script>

<script src="{% static 'js/jquery.formset.js' %}"></script>
{% endblock %}

{% block content %}
   <div class="container">
          {% include 'orders/includes/inc_order_summary.html' %}
       <div class="order_form">
       <form  action="" method="post">
           {% csrf_token %}
           {{ form.as_p }}
           <table class="table">
               {{ orderitems.management_form }}
               {% for form in orderitems.forms %}
                   {% if forloop.first %}
                       <thead>
                       <tr>
                           {% for field in form.visible_fields %}
                               <th class="{% cycle 'td1' 'td2' 'td3' 'td4' %} order formset_td">
                                   {{ field.label|capfirst }}
                               </th>
                           {% endfor %}
                       </tr>
                       </thead>
                   {% endif %}
                   <tr class="formset_row">
                       {% for field in form.visible_fields %}
                       <td class="{% cycle 'td1' 'td2' 'td3' 'td4' %} order formset_td">
                           {% if forloop.first %}
                               {% for hidden in form.hidden_fields %}
                                   {{ hidden }}
                               {% endfor %}
                           {% endif %}
                                {{ field.errors.as_ul }}
                                {% if field.name != 'price' %}
                                    {% cache 3600 orderitemform_product field.value %}
                                        {{ field }}
                                    {% endcache %}
                                {% else %}
                                    {% if field.value %}
                                        <span class="orderitems-{{forloop.parentloop.counter0}}-price">
                                            {{ field.value }}
                                        </span> руб
                                    {% endif %}
                                {% endif %}
                       </td>
                       {% endfor %}
                   </tr>
               {% endfor %}
           </table>
           <button type="submit" value="сохранить" class="btn btn-info btn-block">сохранить</button>
               {% include 'orders/includes/inc_order_actions.html' %}
       </form>
           </div>
   </div>
{% endblock %}

orders/templates/orders/order_read.html
{% extends "products/base.html" %}
{% load static %}

{% block css %}
<link href="{% static 'css/profile.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

<div class="container">
    {% include 'orders/includes/inc_order_summary.html' %}
<div class="row">
{% for item in object.orderitems.select_related %}
        <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
                <img src="{{ item.product.image.url }}"
                     alt="{{ item.product.short_desc }}">
                <div class="card-body">
                    <h4 class="card-title">{{ item.product.name }}</h4>
                    <h6>{{ item.product.price }}&nbspруб x {{ item.quantity }} шт.
                    = {{ item.get_product_cost }}&nbspруб</h6>
                </div>

            </div>
        </div>
    {% endfor %}
</div>
    {% include 'orders/includes/inc_order_actions.html' %}
</div>


{% endblock %}